lang/fsharp: update to 4.1.18
 - add test dependency on libgdiplus
 - update nuget packages
 - update test paths for fsharp assemblies
 - update patches to prevent `nuget restore` from running

ChangeLog:
 - Set executable bit correctly on output
 - Integrate visualfsharp
 - Fix regression on binding redirects for System.Collections.Immutable
 - Fix regression in Microsoft.Build.FSharp.targets
 - Fix binding redirects for System.Collections.Immutable
 - Fix version of library going in %PREFIX/lib/mono/fsharp
 - Align fsc task and target file
 - Use install layout that includes mono/fsharp
 - Fix F# Intereactive on Mono 4.9+
 - Update compiler tools
 - Updates to FSharp.Core nuget package for F# 4.1
 - Fix #656: error FS0193: internal error: No access to the given key